name: Build ESP

on:
  push:
    paths:
      - "esp/**"
      - "!**/README.md"
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: esp-rs/xtensa-toolchain@v1.5
        with:
          default: true
          buildtargets: esp32
          ldproxy: true

      - name: Enable caching
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: esp

      - name: Create config.json
        run: echo '${{ secrets.ESP_CONFIG_JSON }}' | jq '.' > ./esp/config.json

      - name: Run command
        run: cd esp && cargo build --release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: weatherdisplay-esp
          path: ./esp/target/xtensa-esp32-espidf/release/weatherdisplay-esp
